basePath: /
definitions:
    FreeConfig:
        description: 'FreeConfig swagger: model FreeConfig'
        properties:
            entries:
                additionalProperties:
                    type: string
                description: |-
                    Entries map of config options
                    in: map[string]*string
                type: object
                x-go-name: Entries
            id:
                description: |-
                    Id of the config
                    in: string
                type: string
                x-go-name: Id
            version:
                description: |-
                    Version of the config
                    in: string
                type: string
                x-go-name: Version
        type: object
        x-go-package: ars-2023
    FreeGroup:
        description: 'FreeGroup swagger: model FreeGroup'
        properties:
            configs:
                additionalProperties:
                    $ref: '#/definitions/GroupConfig'
                description: |-
                    Entries map of configs
                    in: map[string]*GroupConfig
                type: object
                x-go-name: Configs
            id:
                description: |-
                    Id of the group
                    in: string
                type: string
                x-go-name: Id
            version:
                description: |-
                    Version of the group
                    in: string
                type: string
                x-go-name: Version
        type: object
        x-go-package: ars-2023
    GroupConfig:
        description: 'GroupConfig swagger: model GroupConfig'
        properties:
            entries:
                additionalProperties:
                    type: string
                description: |-
                    Entries of the config
                    in: map[string]*string
                type: object
                x-go-name: Entries
            id:
                description: |-
                    Id of the config
                    in: string
                type: string
                x-go-name: Id
            labels:
                additionalProperties:
                    type: string
                description: |-
                    Labels of the config
                    in: map[string]*string
                type: object
                x-go-name: Labels
        type: object
        x-go-package: ars-2023
info:
    description: 'Title: Config Service API'
    title: Config Service API
    version: 0.0.1
paths:
    /config/:
        post:
            description: Create new configuration
            operationId: createConfig
            parameters:
                - description: 'name: body'
                  in: body
                  name: body
                  required: true
                  schema:
                    $ref: '#/definitions/FreeConfig'
                  x-go-name: Body
            responses:
                "201":
                    description: FreeConfig
                    schema:
                        $ref: '#/definitions/FreeConfig'
                "400":
                    $ref: '#/responses/ErrorResponse'
                "415":
                    $ref: '#/responses/ErrorResponse'
            tags:
                - Configuration
    /config/{id}/{version}/:
        delete:
            description: Delete specific configuration
            operationId: deleteConfig
            parameters:
                - description: |-
                    name: ID
                    description: Entity ID
                  in: path
                  name: id
                  required: true
                  type: string
                  x-go-name: Id
                - description: |-
                    name: Version
                    description: Entity version
                  in: path
                  name: version
                  required: true
                  type: string
                  x-go-name: Version
            responses:
                "201":
                    description: FreeConfig
                    schema:
                        $ref: '#/definitions/FreeConfig'
                "404":
                    $ref: '#/responses/ErrorResponse'
            tags:
                - Configuration
        get:
            description: Get specific configuration
            operationId: getConfig
            parameters:
                - description: |-
                    name: ID
                    description: Entity ID
                  in: path
                  name: id
                  required: true
                  type: string
                  x-go-name: Id
                - description: |-
                    name: Version
                    description: Entity version
                  in: path
                  name: version
                  required: true
                  type: string
                  x-go-name: Version
            responses:
                "200":
                    description: FreeConfig
                    schema:
                        $ref: '#/definitions/FreeConfig'
                "404":
                    $ref: '#/responses/ErrorResponse'
            tags:
                - Configuration
    /config/{id}/all/:
        delete:
            description: Delete all configuration versions
            operationId: deleteConfigVersions
            parameters:
                - description: |-
                    name: ID
                    description: Entity ID
                  in: path
                  name: id
                  required: true
                  type: string
                  x-go-name: Id
            responses:
                "201":
                    description: FreeConfig
                    schema:
                        items:
                            $ref: '#/definitions/FreeConfig'
                        type: array
                "404":
                    $ref: '#/responses/ErrorResponse'
            tags:
                - Configuration
        get:
            description: Get all configuration versions
            operationId: getAllConfigVersions
            parameters:
                - description: |-
                    name: ID
                    description: Entity ID
                  in: path
                  name: id
                  required: true
                  type: string
                  x-go-name: Id
            responses:
                "200":
                    description: FreeConfig
                    schema:
                        items:
                            $ref: '#/definitions/FreeConfig'
                        type: array
                "404":
                    $ref: '#/responses/ErrorResponse'
            tags:
                - Configuration
    /config/all/:
        get:
            description: Get all configurations
            operationId: getAllConfigs
            responses:
                "200":
                    description: FreeConfig
                    schema:
                        items:
                            $ref: '#/definitions/FreeConfig'
                        type: array
                "404":
                    $ref: '#/responses/ErrorResponse'
                "418":
                    $ref: '#/responses/Teapot'
            tags:
                - Configuration
    /group/:
        post:
            description: Create new group
            operationId: createGroup
            parameters:
                - description: 'name: body'
                  in: body
                  name: body
                  required: true
                  schema:
                    $ref: '#/definitions/FreeGroup'
                  x-go-name: Body
            responses:
                "201":
                    description: FreeGroup
                    schema:
                        $ref: '#/definitions/FreeGroup'
                "400":
                    $ref: '#/responses/ErrorResponse'
                "415":
                    $ref: '#/responses/ErrorResponse'
            tags:
                - Group
    /group/{id}/{version}/:
        delete:
            description: Delete specific group
            operationId: deleteGroup
            parameters:
                - description: |-
                    name: ID
                    description: Entity ID
                  in: path
                  name: id
                  required: true
                  type: string
                  x-go-name: Id
                - description: |-
                    name: Version
                    description: Entity version
                  in: path
                  name: version
                  required: true
                  type: string
                  x-go-name: Version
            responses:
                "201":
                    description: FreeGroup
                    schema:
                        $ref: '#/definitions/FreeGroup'
                "404":
                    $ref: '#/responses/ErrorResponse'
            tags:
                - Group
        get:
            description: Get specific group
            operationId: getGroup
            parameters:
                - description: |-
                    name: ID
                    description: Entity ID
                  in: path
                  name: id
                  required: true
                  type: string
                  x-go-name: Id
                - description: |-
                    name: Version
                    description: Entity version
                  in: path
                  name: version
                  required: true
                  type: string
                  x-go-name: Version
            responses:
                "200":
                    description: FreeGroup
                    schema:
                        $ref: '#/definitions/FreeGroup'
                "404":
                    $ref: '#/responses/ErrorResponse'
            tags:
                - Group
    /group/{id}/{version}/{new}/:
        post:
            description: Create new group with appended config
            operationId: appendGroup
            parameters:
                - description: 'name: body'
                  in: body
                  name: configs
                  required: true
                  schema:
                    additionalProperties:
                        $ref: '#/definitions/GroupConfig'
                    type: object
                  x-go-name: Configs
                - description: |-
                    name: ID
                    description: Entity ID
                  in: path
                  name: id
                  required: true
                  type: string
                  x-go-name: Id
                - description: |-
                    name: Version
                    description: Entity version
                  in: path
                  name: version
                  required: true
                  type: string
                  x-go-name: Version
                - description: |-
                    name: Version
                    description: Entity version
                  in: path
                  name: new
                  required: true
                  type: string
                  x-go-name: Version
            responses:
                "201":
                    description: FreeGroup
                    schema:
                        $ref: '#/definitions/FreeGroup'
                "400":
                    $ref: '#/responses/ErrorResponse'
                "403":
                    $ref: '#/responses/ErrorResponse'
                "404":
                    $ref: '#/responses/ErrorResponse'
                "415":
                    $ref: '#/responses/ErrorResponse'
            tags:
                - Group
    /group/{id}/all/:
        delete:
            description: Delete all group versions
            operationId: deleteGroupVersions
            parameters:
                - description: |-
                    name: ID
                    description: Entity ID
                  in: path
                  name: id
                  required: true
                  type: string
                  x-go-name: Id
            responses:
                "201":
                    description: FreeGroup
                    schema:
                        items:
                            $ref: '#/definitions/FreeGroup'
                        type: array
                "404":
                    $ref: '#/responses/ErrorResponse'
            tags:
                - Group
        get:
            description: Get all group versions
            operationId: getAllGroupVersions
            parameters:
                - description: |-
                    name: ID
                    description: Entity ID
                  in: path
                  name: id
                  required: true
                  type: string
                  x-go-name: Id
            responses:
                "200":
                    description: FreeGroup
                    schema:
                        items:
                            $ref: '#/definitions/FreeGroup'
                        type: array
                "404":
                    $ref: '#/responses/ErrorResponse'
            tags:
                - Group
    /group/all/:
        get:
            description: Get all groups
            operationId: getAllGroups
            responses:
                "200":
                    description: FreeGroup
                    schema:
                        items:
                            $ref: '#/definitions/FreeGroup'
                        type: array
                "404":
                    $ref: '#/responses/ErrorResponse'
                "418":
                    $ref: '#/responses/Teapot'
            tags:
                - Group
produces:
    - application/json
responses:
    ErrorResponse:
        description: ""
        headers:
            message:
                description: |-
                    Message of the error
                    in: string
                type: string
            status:
                description: |-
                    Error status code
                    in: int64
                format: int64
                type: integer
    Teapot:
        description: ""
        headers:
            message:
                description: |-
                    Message of the error
                    in: string
                type: string
            status:
                description: |-
                    Error status code
                    in: int64
                format: int64
                type: integer
schemes:
    - http
swagger: "2.0"
